### ISSUE TITLE
Rolling window implementation

### ISSUE THREAD

**Issue by MislavSag** [hendersontrent/theft#113]
I would like to make big feature request.

In most times, we want to calculate features on rolling window.

I would like to recommend runner R package for making rolling versions of feature calculations. 

I have already done that for some financial time series data and my own features . Here is a template I ussually use:
```
rolling_f <- function(df, row_index = 1:nrow(df), windows = c(100, 200), workers = 4L) {

  # solve No visible binding for global variable
  price = `.` = NULL

  # checks
  testSubset(c("symbol", "close"), colnames(prices_panel))
  assert_double(prices_panel$close, lower = 1e-005)

  # prepare data
  prices_sample <- prices_panel[, .(symbol, date, close)]

  # start cluster
  cl <- makeCluster(workers)
  clusterExport(cl, "prices_sample", envir = environment())
  clusterCall(cl, function() library(Rcatch22))
  clusterCall(cl, function() library(data.table))

  # rolling arima forecasts
  data_list <- list()
  for (i in 1:length(windows)) {
    rolling_data <- runner(
      x = prices_sample,
      f = function(x) {

        # some functuion

      },
      k = windows[i],
      at = row_index,
      na_pad = TRUE,
      simplify = FALSE,
      cl = cl
    )
    gc()
    data_list[[i]] <- rbindlist(rolling_data[lengths(rolling_data) > 1L], fill = TRUE)
  }
  stopCluster(cl)
  data_all_windows <- Reduce(function(x, y) merge(x, y, by = c("symbol", "date"), all.x = TRUE, all.y = TRUE), data_list)
  return(data_all_windows)
}
```

**Comment by XavierFPMorris** [comment]
🤔

**Comment by hendersontrent** [comment]
Hi. 2 suggestions: (i) Please code up the function yourself and submit a PR as this isn't an active area of development for myself and `theft` currently; or (ii) use `theft` as-is, but just call it within your existing rolling window function. For the latter, you can subset your data frame within the for loop and pass the subsetted data frame into `theft` for each iteration. I'm going to close this issue for now.
