### ISSUE TITLE
Recommend using mlr3

### ISSUE THREAD

**Issue by MislavSag** [hendersontrent/theft#152]
Hi,
I was skimming the package today after some time.

I would like to recommend mlr3fselect package for important feature selection.

In few line of code it is possible to extract important features using different resampling, learners, tasks and optimization methods.

**Comment by hendersontrent** [comment]
Closing this as we have a top feature performance function coded off the theoretical basis used originally in [`hctsa`](https://github.com/benfulcher/hctsa) and want to minimise (the already large) package dependencies.
