### ISSUE TITLE
summarise() deprecated in dplyr

### ISSUE THREAD

**Issue by IssyMiddleton** [hendersontrent/theft#249]
Just running the examples and have received warning about deprecated code in dplyr(). Asks the user to report it to you.

> simData = simData
> View(simData)
> feature_matrix <- calculate_features(data = simData, 
+                                      id_var = "id", 
+                                      time_var = "timepoint", 
+                                      values_var = "values", 
+                                      group_var = "process", 
+                                      feature_set = "catch22",
+                                      seed = 123)
No IDs removed. All value vectors good for feature extraction.
Running computations for catch22...

Calculations completed for catch22.
Warning messages:
1: There was 1 warning in `dplyr::summarise()`.
ℹ In argument: `Rcatch22::catch22_all(.data$values, catch24 = catch24)`.
ℹ In group 1: `id = "AR(1)_1"`, `group = "AR(1)"`.
Caused by warning:
! As of 0.1.14 the feature 'CO_f1ecac' returns a double instead of int
This warning is displayed once per session. 
2: Returning more (or less) than 1 row per `summarise()` group was deprecated in dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()` always returns an ungrouped
  data frame and adjust accordingly.
ℹ The deprecated feature was likely used in the theft package.
  Please report the issue at <https://github.com/hendersontrent/theft/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

**Comment by hendersontrent** [comment]
Thanks. Yeah I have seen this a lot in both `theft` and all my work using the `tidyverse` -- it would take me a while to refactor everything to `reframe()` and I have not had the time to go through it systematically yet. It's on my to-do list!
